// movies saga
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_GENRE = 'FETCH_MOVIES_GENRE';
export const FETCH_MOVIES_CAST = 'FETCH_MOVIES_CAST';
export const ACTIVE_MOVIE = 'ACTIVE_MOVIE';
// movies reducer
export const FETCH_MOVIES_FAILED = 'FETCH_MOVIES_FAILED';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_GENRE_SUCCESS = 'FETCH_MOVIES_GENRE_SUCCESS';
export const FETCH_MOVIES_CAST_SUCCESS = 'FETCH_MOVIES_CAST_SUCCESS';
export const SET_ACTIVE_MOVIE = 'SET_ACTIVE_MOVIE';
export const SET_ACTIVE_FILTER = 'SET_ACTIVE_FILTER';

// navigation reducer
export const CHANGE_MOBILE = 'CHANGE_MOBILE';
export const IS_LOADING = 'IS_LOADING';
export const SHOW_MOVIE_DETAILS = 'SHOW_MOVIE_DETAILS';
export const SHOW_ALL_MOVIES = 'SHOW_ALL_MOVIES';