export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_FAILED = 'FETCH_MOVIES_FAILED';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const ACTIVE_MOVIE = 'ACTIVE_MOVIE';
export const SET_ACTIVE_MOVIE = 'SET_ACTIVE_MOVIE';