// movies saga
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MORE_MOVIES = 'FETCH_MORE_MOVIES';
export const FETCH_MOVIES_GENRE = 'FETCH_MOVIES_GENRE';
export const FETCH_MOVIES_CAST = 'FETCH_MOVIES_CAST';
export const FETCH_MOVIE_TRAILER = 'FETCH_MOVIE_TRAILER';
export const FETCH_MOVIES_DISCOVER = 'FETCH_MOVIES_DISCOVER';
export const ACTIVE_MOVIE = 'ACTIVE_MOVIE';
// movies reducer
export const FETCH_MOVIES_FAILED = 'FETCH_MOVIES_FAILED';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MORE_MOVIES_SUCCESS = 'FETCH_MORE_MOVIES_SUCCESS';
export const FETCH_MOVIES_GENRE_SUCCESS = 'FETCH_MOVIES_GENRE_SUCCESS';
export const FETCH_MOVIES_CAST_SUCCESS = 'FETCH_MOVIES_CAST_SUCCESS';
export const SET_ACTIVE_MOVIE = 'SET_ACTIVE_MOVIE';
export const SET_ACTIVE_FILTER = 'SET_ACTIVE_FILTER';
export const SET_PARAMS = 'SET_PARAMS';
export const FETCH_MOVIE_TRAILER_SUCCESS = 'FETCH_MOVIE_TRAILER_SUCCESS';
export const FETCH_MOVIE_TRAILER_FAILED = 'FETCH_MOVIE_TRAILER_FAILED';
export const LOADING_CAST = 'LOADING_CAST';

// navigation reducer
export const CHANGE_MOBILE = 'CHANGE_MOBILE';
export const LOADED = 'LOADED';
export const SHOW_MOVIE_DETAILS = 'SHOW_MOVIE_DETAILS';
export const SHOW_ALL_MOVIES = 'SHOW_ALL_MOVIES';
export const UPDATE_SCROLL_POSITION = 'UPDATE_SCROLL_POSITION';
export const SHOW_MODAL = 'SHOW_MODAL';